In [45]:
import numpy as np

In [46]:
# 1D array

a = np.array([1, 2, -1, 4])
b = np.array([1, 0, -2, 3])

print(a + b)
print(a * b)



# 2D numpy array matrices

A1 = np.array([[1, 1], [0, 1]])
print(A1)

A2 = np.array([[2, 0], [-1, 0]])
print(A2)

print(A1 + A2)
print(A1 * A2) # This is element-wise multiplication, not matrix multiplication


n = np.dot(A1, A2)
print(n)


# Column Vector of size 2 by 

v = np.array([[1], [2]])
print(v)
print(v.shape)

print()
print(np.dot(A1, v))

[ 2  2 -3  7]
[ 1  0  2 12]
[[1 1]
 [0 1]]
[[ 2  0]
 [-1  0]]
[[ 3  1]
 [-1  1]]
[[2 0]
 [0 0]]
[[ 1  0]
 [-1  0]]
[[1]
 [2]]
(2, 1)

[[3]
 [2]]


In [47]:
def matrix_power(A, m): # A is a square matrix so that we can multiply it by itself n times 

    p = 1

    for i in range(m):
        p = np.dot(p, A)
    return p 

B = matrix_power(A1, 2)
    
print(B)

[[1 2]
 [0 1]]


In [48]:
def matrix_power_while(A, m):  

    i = 1

    while i <= m:
        p = np.dot(p,A)
     
        i += 1
    return p

In [49]:
def number_power(x,n):

    p = 1 

    while n > 0:
        if n % 2 == 1:
            p = p * x
        x + x*x
        n = n // 2
    return p

print(number_power(2, 3))

4


In [50]:
def matrix_power_fast(A, m):
    result = np.eye(A.shape[0], dtype=int)  # Initialize result as the identity matrix
    base = A.copy()
    
    while m > 0:
        if m % 2 == 1:
            result = np.dot(result, base)
        base = np.dot(base, base)
        m //= 2
    
    return result

# Define the matrix
test_matrix = np.array([[1, 2], [3, 4]])

# Test the matrix_power_fast function
result = matrix_power_fast(test_matrix, 2)
print(result)





[[ 7 10]
 [15 22]]


In [51]:
def fibonacci(n):
    return 1
    
A = np.array ([[1, 1], [1, 0]])
initial_values = np.array([[1], [1]])
power = matrix_power_fast(A, n-1)
result = np.dot(power, initial_values)
return result

print(fibonacci(3))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
def recursive(m,n):

    # to write a recursive function to calculate the steps needed to move on a grid of size m by n from the top left corner to the bottom right corner

    if m == 0 or n == 0:
        return 1
    else:
        return recursive(m-1, n) + recursive(m, n-1)
    
print(recursive(2,3))

# for (m,n) how many function calls are made: 2^(m+n) 
    

10


In [ ]:
def iterative_solution(m,n):

# to write an iterative function to calculate the steps needed to move on a grid of size m by n from the top left corner to the bottom right corner

    grid = np.zeros((m+1, n+1), dtype=int) # create a grid of size m+1 by n+1
    grid[0,0] = 1 # set the top left corner to 1

    for i in range(m+1): # iterate over the rows
        for j in range(n+1): # iterate over the columns
            if i > 0: # if we are not in the first row
                grid[i,j] += grid[i-1,j] # add the value from the cell above
            if j > 0: # if we are not in the first column
                grid[i,j] += grid[i,j-1] # add the value from the cell to the left
    return grid[m,n] # return the value in the bottom right corner

print(iterative_solution(2,3)) # 10





10
